export const CONTRACT_CONFIG = {
  APP_ID: Number(import.meta.env.VITE_APP_ID || 761815545),
  APP_ADDRESS: import.meta.env.VITE_APP_ADDRESS || 'IFZ66VGETANO5BTJLZEOHWUHOX3JZJOS6KGA3JVAN3MEGL6TWRLASGETRI',
};
